version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - '3006:3006'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '1337:1337'
